/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MentalRouteImport } from './routes/mental'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as IndexRouteImport } from './routes/index'

const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalRoute = MentalRouteImport.update({
  id: '/mental',
  path: '/mental',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fitness': typeof FitnessRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/mental': typeof MentalRoute
  '/signup': typeof SignupRoute
  '/sleep': typeof SleepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fitness': typeof FitnessRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/mental': typeof MentalRoute
  '/signup': typeof SignupRoute
  '/sleep': typeof SleepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fitness': typeof FitnessRoute
  '/login': typeof LoginRoute
  '/meals': typeof MealsRoute
  '/mental': typeof MentalRoute
  '/signup': typeof SignupRoute
  '/sleep': typeof SleepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fitness'
    | '/login'
    | '/meals'
    | '/mental'
    | '/signup'
    | '/sleep'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fitness' | '/login' | '/meals' | '/mental' | '/signup' | '/sleep'
  id:
    | '__root__'
    | '/'
    | '/fitness'
    | '/login'
    | '/meals'
    | '/mental'
    | '/signup'
    | '/sleep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FitnessRoute: typeof FitnessRoute
  LoginRoute: typeof LoginRoute
  MealsRoute: typeof MealsRoute
  MentalRoute: typeof MentalRoute
  SignupRoute: typeof SignupRoute
  SleepRoute: typeof SleepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental': {
      id: '/mental'
      path: '/mental'
      fullPath: '/mental'
      preLoaderRoute: typeof MentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FitnessRoute: FitnessRoute,
  LoginRoute: LoginRoute,
  MealsRoute: MealsRoute,
  MentalRoute: MentalRoute,
  SignupRoute: SignupRoute,
  SleepRoute: SleepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
